# Generated by Django 4.2.6 on 2023-10-30 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsAndStatus',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='fld_comment', max_length=255)),
                ('status', models.CharField(choices=[('L', 'LIKE'), ('D', 'DISLIKE'), ('H', 'HEART'), ('N', 'NOTHING')], db_column='fld_status', default='N', max_length=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fld_updated_at')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_comments_n_status',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('tweet', models.CharField(db_column='fld_tweet', max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fld_updated_at')),
                ('comments', models.ManyToManyField(db_column='fld_comments', to='database.commentsandstatus')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_tweet',
            },
        ),
    ]
