# Generated by Django 4.2.6 on 2023-10-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentsandstatus',
            name='tweet_id',
            field=models.ForeignKey(blank=True, db_column='fld_tweet_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.tweet'),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='fld_name', max_length=100, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fld_updated_at')),
                ('tweets', models.ManyToManyField(db_column='fld_tweets', related_name='hashtags', to='database.tweet')),
            ],
            options={
                'db_table': 'tbl_hashtag',
            },
        ),
    ]
