# Generated by Django 4.2.6 on 2023-11-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_tweet_comments_commentsandstatus_tweet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTable',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='fld_name', max_length=100, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fld_updated_at')),
            ],
            options={
                'db_table': 'tbl_dummy',
            },
        ),
        migrations.CreateModel(
            name='MappingHashtags',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('DummyTable', models.ForeignKey(blank=True, db_column='fld_dummy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.dummytable')),
                ('hashtag_id', models.ForeignKey(blank=True, db_column='fld_hashtag_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.hashtag')),
            ],
            options={
                'db_table': 'tbl_mapping_hashtags',
            },
        ),
        migrations.AddField(
            model_name='dummytable',
            name='hashtag',
            field=models.ManyToManyField(db_column='fld_hashtags', related_name='hashtags_relation', through='database.MappingHashtags', to='database.hashtag'),
        ),
    ]
