# Generated by Django 4.2.6 on 2023-11-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_dummytabletwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummytabletwo',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='mappinghashtags',
            name='DummyTable',
        ),
        migrations.RemoveField(
            model_name='mappinghashtags',
            name='hashtag_id',
        ),
        migrations.DeleteModel(
            name='DummyTable',
        ),
        migrations.DeleteModel(
            name='DummyTableTwo',
        ),
        migrations.DeleteModel(
            name='MappingHashtags',
        ),
    ]
