# Generated by Django 4.2.6 on 2023-11-21 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0006_alter_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsandstatus',
            name='comment',
            field=models.CharField(db_column='comment', max_length=255),
        ),
        migrations.AlterField(
            model_name='commentsandstatus',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='created_datetime'),
        ),
        migrations.AlterField(
            model_name='commentsandstatus',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commentsandstatus',
            name='status',
            field=models.CharField(choices=[('L', 'LIKE'), ('D', 'DISLIKE'), ('H', 'HEART'), ('N', 'NOTHING')], db_column='status', default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='commentsandstatus',
            name='tweet_id',
            field=models.ForeignKey(blank=True, db_column='tweet_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.tweet'),
        ),
        migrations.AlterField(
            model_name='commentsandstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='commentsandstatus',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='created_datetime'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(db_column='name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(db_column='tweets', related_name='hashtags', to='database.tweet'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='created_datetime'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(db_column='tweet', max_length=255),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
