# Generated by Django 4.2.6 on 2023-11-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_commentsandstatus_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='tweet',
        ),
    ]
