# Generated by Django 4.2.6 on 2023-11-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_tweet_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentsandstatus',
            table='comments_n_status',
        ),
        migrations.AlterModelTable(
            name='hashtag',
            table='hashtag',
        ),
    ]
