# Generated by Django 4.2.6 on 2023-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True, verbose_name='last login'),
        ),
    ]
