# Generated by Django 4.2.6 on 2023-11-21 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(db_column='address', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='created_datetime', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(db_column='followers', db_table='tbl_user_follows', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_column='is_admin', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_column='mobile', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='raw_password',
            field=models.CharField(db_column='raw_password', default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
    ]
