# Generated by Django 4.2.6 on 2023-11-21 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_address_alter_user_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(db_column='followers', db_table='user_follows', related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
